//! PDF evidence report generation using printpdf.
//!
//! Produces an auditor-ready multi-page PDF from an [`EvidenceReport`].

use printpdf::{
    BuiltinFont, Mm, Op, PdfDocument, PdfFontHandle, PdfPage, PdfSaveOptions, Point, Pt, TextItem,
};

use super::report::EvidenceReport;
use crate::Result;

const PAGE_WIDTH_MM: f32 = 210.0;
const PAGE_HEIGHT_MM: f32 = 297.0;
const MARGIN_MM: f32 = 25.0;

/// Generate a PDF evidence report and return the raw bytes.
///
/// `report_sha256` is the digest of the exact stored report JSON bytes
/// (contract v2); it is computed after serialization and therefore passed in
/// rather than read from the report. When `None` (legacy schema 1.0
/// reports), the embedded `integrity.report_sha256` field is shown instead.
pub fn generate_pdf(report: &EvidenceReport, report_sha256: Option<&str>) -> Result<Vec<u8>> {
    let mut doc = PdfDocument::new("Kafka Backup Validation Evidence Report");

    let mut cover = PageBuilder::new();
    cover.title("Kafka Backup Validation");
    cover.title("Evidence Report");
    cover.space(5.0);
    cover.heading(format!(
        "Overall Result: {}",
        report.validation.overall_result
    ));
    cover.space(3.0);
    cover.body(format!("Report ID: {}", report.report_id));
    cover.body(format!("Generated: {}", report.generated_at));
    cover.body(format!(
        "Tool: {} v{}",
        report.tool.name, report.tool.version
    ));
    if let Some(triggered_by) = &report.triggered_by {
        cover.body(format!("Triggered by: {triggered_by}"));
    }
    cover.space(5.0);
    cover.heading("Backup Summary");
    cover.body(format!("Backup ID: {}", report.backup.id));
    cover.body(format!(
        "Topics: {}  Partitions: {}  Segments: {}",
        report.backup.total_topics, report.backup.total_partitions, report.backup.total_segments
    ));
    cover.body(format!("Total records: {}", report.backup.total_records));
    cover.body(format!("Storage: {}", report.backup.storage_backend));
    cover.footer("Generated by OSO Kafka Backup - https://kafkabackup.com");

    let mut validation = PageBuilder::new();
    validation.heading("Validation Check Results");
    validation.body(format!(
        "Checks: {}/{} passed | {} failed | {} skipped | Duration: {} ms",
        report.validation.checks_passed,
        report.validation.checks_total,
        report.validation.checks_failed,
        report.validation.checks_skipped,
        report.validation.total_duration_ms
    ));
    validation.space(3.0);
    for result in &report.validation.results {
        validation.subheading(format!(
            "{}: {} ({} ms)",
            result.check_name, result.outcome, result.duration_ms
        ));
        validation.body(truncate(&result.detail, 120));
    }
    validation.footer("Page 2 - Validation Results");

    let mut integrity = PageBuilder::new();
    integrity.heading("Integrity and Signing");
    for line in integrity_display_lines(report, report_sha256) {
        integrity.body(line);
    }
    integrity.space(5.0);
    integrity.heading("Compliance Framework Mappings");
    if let Some(sox) = &report.compliance_mappings.sox_itgc {
        integrity.subheading("SOX ITGC");
        integrity.body(format!("Control: {}", sox.control));
        integrity.body(format!("Satisfied by: {}", sox.satisfied_by.join(", ")));
        integrity.body(format!(
            "Retention: {} days configured ({} years required)",
            sox.evidence_retention_configured_days, sox.evidence_retention_required_years
        ));
    }
    if let Some(cmmc) = &report.compliance_mappings.cmmc_l2 {
        integrity.subheading("CMMC Level 2");
        integrity.body(format!("Control: {} - {}", cmmc.control, cmmc.description));
        integrity.body(format!("Satisfied by: {}", cmmc.satisfied_by.join(", ")));
    }
    if let Some(gdpr) = &report.compliance_mappings.gdpr_art32 {
        integrity.subheading("GDPR Article 32");
        integrity.body(format!("Control: {}", gdpr.control));
        integrity.body(format!("Satisfied by: {}", gdpr.satisfied_by.join(", ")));
        if let Some(rto) = gdpr.rto_demonstrated_seconds {
            integrity.body(format!("RTO demonstrated: {rto} seconds"));
        }
    }
    integrity.footer("Page 3 - Integrity and Compliance Mappings");

    let pages = vec![cover.finish(), validation.finish(), integrity.finish()];
    let mut warnings = Vec::new();
    Ok(doc
        .with_pages(pages)
        .save(&PdfSaveOptions::default(), &mut warnings))
}

/// The exact lines rendered on the PDF's "Integrity and Signing" page.
///
/// Public so regression tests can assert the PDF displays the same external
/// digest the CLI prints (the PDF body streams are compressed, so tests
/// verify the rendered source of truth instead of parsing the PDF).
pub fn integrity_display_lines(
    report: &EvidenceReport,
    report_sha256: Option<&str>,
) -> Vec<String> {
    let mut lines = vec![format!(
        "Manifest SHA-256: {}",
        report.integrity.backup_manifest_sha256
    )];
    match report_sha256 {
        Some(digest) => {
            lines.push(format!("Report SHA-256 (stored JSON bytes): {digest}"));
        }
        None if !report.integrity.report_sha256.is_empty() => {
            lines.push(format!(
                "Report SHA-256 (legacy, embedded): {}",
                report.integrity.report_sha256
            ));
        }
        None => {
            lines.push("Report SHA-256: not available".to_string());
        }
    }
    lines.push(format!(
        "Checksums valid: {}",
        report.integrity.checksums_valid
    ));
    lines.push(format!(
        "Signature algorithm: {}",
        report.integrity.signature_algorithm
    ));
    if let Some(signer) = &report.integrity.signed_by {
        lines.push(format!("Signed by: {signer}"));
    }
    lines
}

struct PageBuilder {
    ops: Vec<Op>,
    y_mm: f32,
}

impl PageBuilder {
    fn new() -> Self {
        Self {
            ops: Vec::new(),
            y_mm: PAGE_HEIGHT_MM - MARGIN_MM,
        }
    }

    fn title(&mut self, text: impl Into<String>) {
        self.line(text, BuiltinFont::HelveticaBold, 24.0, 10.0);
    }

    fn heading(&mut self, text: impl Into<String>) {
        self.line(text, BuiltinFont::HelveticaBold, 14.0, 8.0);
    }

    fn subheading(&mut self, text: impl Into<String>) {
        self.line(text, BuiltinFont::HelveticaBold, 10.0, 6.0);
    }

    fn body(&mut self, text: impl Into<String>) {
        self.line(text, BuiltinFont::Helvetica, 9.0, 5.0);
    }

    fn line(&mut self, text: impl Into<String>, font: BuiltinFont, size: f32, advance: f32) {
        if self.y_mm <= MARGIN_MM + 10.0 {
            return;
        }
        self.ops.extend([
            Op::StartTextSection,
            Op::SetTextCursor {
                pos: Point::new(Mm(MARGIN_MM), Mm(self.y_mm)),
            },
            Op::SetFont {
                font: PdfFontHandle::Builtin(font),
                size: Pt(size),
            },
            Op::ShowText {
                items: vec![TextItem::Text(text.into())],
            },
            Op::EndTextSection,
        ]);
        self.y_mm -= advance;
    }

    fn space(&mut self, millimetres: f32) {
        self.y_mm -= millimetres;
    }

    fn footer(&mut self, text: impl Into<String>) {
        let saved_y = self.y_mm;
        self.y_mm = MARGIN_MM;
        self.line(text, BuiltinFont::Helvetica, 8.0, 0.0);
        self.y_mm = saved_y;
    }

    fn finish(self) -> PdfPage {
        PdfPage::new(Mm(PAGE_WIDTH_MM), Mm(PAGE_HEIGHT_MM), self.ops)
    }
}

fn truncate(value: &str, max_chars: usize) -> String {
    let mut chars = value.chars();
    let prefix: String = chars.by_ref().take(max_chars).collect();
    if chars.next().is_some() {
        format!("{prefix}...")
    } else {
        prefix
    }
}
