//! PDF evidence report generation using printpdf.
//!
//! Produces an auditor-ready multi-page PDF from an [`EvidenceReport`].

use printpdf::*;
use std::io::BufWriter;

use super::report::EvidenceReport;
use crate::Result;

const PAGE_WIDTH_MM: f32 = 210.0;
const PAGE_HEIGHT_MM: f32 = 297.0;
const MARGIN_MM: f32 = 25.0;
const FONT_SIZE_TITLE: f32 = 24.0;
const FONT_SIZE_HEADING: f32 = 14.0;
const FONT_SIZE_BODY: f32 = 10.0;
const FONT_SIZE_SMALL: f32 = 8.0;
const LINE_HEIGHT: f32 = 5.0;

/// Generate a PDF evidence report and return the raw bytes.
pub fn generate_pdf(report: &EvidenceReport) -> Result<Vec<u8>> {
    let (doc, page1, layer1) = PdfDocument::new(
        "Kafka Backup Validation Evidence Report",
        Mm(PAGE_WIDTH_MM),
        Mm(PAGE_HEIGHT_MM),
        "Cover",
    );

    let font = doc
        .add_builtin_font(BuiltinFont::Helvetica)
        .map_err(|e| crate::Error::Evidence(format!("Failed to load font: {e}")))?;
    let font_bold = doc
        .add_builtin_font(BuiltinFont::HelveticaBold)
        .map_err(|e| crate::Error::Evidence(format!("Failed to load bold font: {e}")))?;

    // === Page 1: Cover ===
    let layer = doc.get_page(page1).get_layer(layer1);
    let mut y = PAGE_HEIGHT_MM - MARGIN_MM;

    // Title
    write_text(
        &layer,
        &font_bold,
        FONT_SIZE_TITLE,
        MARGIN_MM,
        y,
        "Kafka Backup Validation",
    );
    y -= 10.0;
    write_text(
        &layer,
        &font_bold,
        FONT_SIZE_TITLE,
        MARGIN_MM,
        y,
        "Evidence Report",
    );
    y -= 15.0;

    // Result badge
    let result_text = format!("Overall Result: {}", report.validation.overall_result);
    write_text(
        &layer,
        &font_bold,
        FONT_SIZE_HEADING,
        MARGIN_MM,
        y,
        &result_text,
    );
    y -= 10.0;

    // Metadata
    write_text(
        &layer,
        &font,
        FONT_SIZE_BODY,
        MARGIN_MM,
        y,
        &format!("Report ID: {}", report.report_id),
    );
    y -= LINE_HEIGHT;
    write_text(
        &layer,
        &font,
        FONT_SIZE_BODY,
        MARGIN_MM,
        y,
        &format!("Generated: {}", report.generated_at),
    );
    y -= LINE_HEIGHT;
    write_text(
        &layer,
        &font,
        FONT_SIZE_BODY,
        MARGIN_MM,
        y,
        &format!("Tool: {} v{}", report.tool.name, report.tool.version),
    );
    y -= LINE_HEIGHT;
    if let Some(ref triggered) = report.triggered_by {
        write_text(
            &layer,
            &font,
            FONT_SIZE_BODY,
            MARGIN_MM,
            y,
            &format!("Triggered by: {triggered}"),
        );
        y -= LINE_HEIGHT;
    }
    y -= 5.0;

    // Backup summary
    write_text(
        &layer,
        &font_bold,
        FONT_SIZE_HEADING,
        MARGIN_MM,
        y,
        "Backup Summary",
    );
    y -= 7.0;
    write_text(
        &layer,
        &font,
        FONT_SIZE_BODY,
        MARGIN_MM,
        y,
        &format!("Backup ID: {}", report.backup.id),
    );
    y -= LINE_HEIGHT;
    write_text(
        &layer,
        &font,
        FONT_SIZE_BODY,
        MARGIN_MM,
        y,
        &format!(
            "Topics: {}  Partitions: {}  Segments: {}",
            report.backup.total_topics,
            report.backup.total_partitions,
            report.backup.total_segments
        ),
    );
    y -= LINE_HEIGHT;
    write_text(
        &layer,
        &font,
        FONT_SIZE_BODY,
        MARGIN_MM,
        y,
        &format!("Total Records: {}", report.backup.total_records),
    );
    y -= LINE_HEIGHT;
    write_text(
        &layer,
        &font,
        FONT_SIZE_BODY,
        MARGIN_MM,
        y,
        &format!("Storage: {}", report.backup.storage_backend),
    );
    let _ = y; // remaining vertical space on cover page

    // Footer
    write_text(
        &layer,
        &font,
        FONT_SIZE_SMALL,
        MARGIN_MM,
        MARGIN_MM,
        "Generated by OSO Kafka Backup — https://kafkabackup.com",
    );

    // === Page 2: Validation Results ===
    let (page2, layer2) = doc.add_page(Mm(PAGE_WIDTH_MM), Mm(PAGE_HEIGHT_MM), "Validation Results");
    let layer = doc.get_page(page2).get_layer(layer2);
    y = PAGE_HEIGHT_MM - MARGIN_MM;

    write_text(
        &layer,
        &font_bold,
        FONT_SIZE_HEADING,
        MARGIN_MM,
        y,
        "Validation Check Results",
    );
    y -= 10.0;

    let summary_line = format!(
        "Checks: {}/{} passed  |  {} failed  |  {} skipped  |  Duration: {}ms",
        report.validation.checks_passed,
        report.validation.checks_total,
        report.validation.checks_failed,
        report.validation.checks_skipped,
        report.validation.total_duration_ms,
    );
    write_text(&layer, &font, FONT_SIZE_BODY, MARGIN_MM, y, &summary_line);
    y -= 8.0;

    // Table header
    write_text(
        &layer,
        &font_bold,
        FONT_SIZE_BODY,
        MARGIN_MM,
        y,
        "Check Name",
    );
    write_text(&layer, &font_bold, FONT_SIZE_BODY, 90.0, y, "Result");
    write_text(&layer, &font_bold, FONT_SIZE_BODY, 115.0, y, "Duration");
    write_text(&layer, &font_bold, FONT_SIZE_BODY, 140.0, y, "Detail");
    y -= LINE_HEIGHT;

    for result in &report.validation.results {
        if y < MARGIN_MM + 10.0 {
            break; // Avoid overflowing the page
        }
        write_text(
            &layer,
            &font,
            FONT_SIZE_BODY,
            MARGIN_MM,
            y,
            &result.check_name,
        );
        write_text(
            &layer,
            &font,
            FONT_SIZE_BODY,
            90.0,
            y,
            &result.outcome.to_string(),
        );
        write_text(
            &layer,
            &font,
            FONT_SIZE_BODY,
            115.0,
            y,
            &format!("{}ms", result.duration_ms),
        );
        // Truncate detail to fit
        let detail = if result.detail.len() > 50 {
            format!("{}...", &result.detail[..47])
        } else {
            result.detail.clone()
        };
        write_text(&layer, &font, FONT_SIZE_SMALL, 140.0, y, &detail);
        y -= LINE_HEIGHT;
    }

    let _ = y; // remaining vertical space
               // Footer
    write_text(
        &layer,
        &font,
        FONT_SIZE_SMALL,
        MARGIN_MM,
        MARGIN_MM,
        "Page 2 — Validation Results",
    );

    // === Page 3: Integrity & Compliance ===
    let (page3, layer3) = doc.add_page(
        Mm(PAGE_WIDTH_MM),
        Mm(PAGE_HEIGHT_MM),
        "Integrity & Compliance",
    );
    let layer = doc.get_page(page3).get_layer(layer3);
    y = PAGE_HEIGHT_MM - MARGIN_MM;

    write_text(
        &layer,
        &font_bold,
        FONT_SIZE_HEADING,
        MARGIN_MM,
        y,
        "Integrity & Signing",
    );
    y -= 8.0;
    write_text(
        &layer,
        &font,
        FONT_SIZE_BODY,
        MARGIN_MM,
        y,
        &format!(
            "Manifest SHA-256: {}",
            report.integrity.backup_manifest_sha256
        ),
    );
    y -= LINE_HEIGHT;
    write_text(
        &layer,
        &font,
        FONT_SIZE_BODY,
        MARGIN_MM,
        y,
        &format!("Report SHA-256: {}", report.integrity.report_sha256),
    );
    y -= LINE_HEIGHT;
    write_text(
        &layer,
        &font,
        FONT_SIZE_BODY,
        MARGIN_MM,
        y,
        &format!(
            "Signature Algorithm: {}",
            report.integrity.signature_algorithm
        ),
    );
    y -= LINE_HEIGHT;
    if let Some(ref signer) = report.integrity.signed_by {
        write_text(
            &layer,
            &font,
            FONT_SIZE_BODY,
            MARGIN_MM,
            y,
            &format!("Signed By: {signer}"),
        );
        y -= LINE_HEIGHT;
    }
    y -= 10.0;

    write_text(
        &layer,
        &font_bold,
        FONT_SIZE_HEADING,
        MARGIN_MM,
        y,
        "Compliance Framework Mappings",
    );
    y -= 8.0;

    if let Some(ref sox) = report.compliance_mappings.sox_itgc {
        write_text(&layer, &font_bold, FONT_SIZE_BODY, MARGIN_MM, y, "SOX ITGC");
        y -= LINE_HEIGHT;
        write_text(
            &layer,
            &font,
            FONT_SIZE_BODY,
            MARGIN_MM,
            y,
            &format!("Control: {}", sox.control),
        );
        y -= LINE_HEIGHT;
        write_text(
            &layer,
            &font,
            FONT_SIZE_BODY,
            MARGIN_MM,
            y,
            &format!("Satisfied by: {}", sox.satisfied_by.join(", ")),
        );
        y -= LINE_HEIGHT;
        write_text(
            &layer,
            &font,
            FONT_SIZE_BODY,
            MARGIN_MM,
            y,
            &format!(
                "Retention: {} days configured ({}y required)",
                sox.evidence_retention_configured_days, sox.evidence_retention_required_years
            ),
        );
        y -= 7.0;
    }

    if let Some(ref cmmc) = report.compliance_mappings.cmmc_l2 {
        write_text(
            &layer,
            &font_bold,
            FONT_SIZE_BODY,
            MARGIN_MM,
            y,
            "CMMC Level 2",
        );
        y -= LINE_HEIGHT;
        write_text(
            &layer,
            &font,
            FONT_SIZE_BODY,
            MARGIN_MM,
            y,
            &format!("Control: {} — {}", cmmc.control, cmmc.description),
        );
        y -= LINE_HEIGHT;
        write_text(
            &layer,
            &font,
            FONT_SIZE_BODY,
            MARGIN_MM,
            y,
            &format!("Satisfied by: {}", cmmc.satisfied_by.join(", ")),
        );
        y -= 7.0;
    }

    if let Some(ref gdpr) = report.compliance_mappings.gdpr_art32 {
        write_text(
            &layer,
            &font_bold,
            FONT_SIZE_BODY,
            MARGIN_MM,
            y,
            "GDPR Article 32",
        );
        y -= LINE_HEIGHT;
        write_text(
            &layer,
            &font,
            FONT_SIZE_BODY,
            MARGIN_MM,
            y,
            &format!("Control: {}", gdpr.control),
        );
        y -= LINE_HEIGHT;
        if let Some(rto) = gdpr.rto_demonstrated_seconds {
            write_text(
                &layer,
                &font,
                FONT_SIZE_BODY,
                MARGIN_MM,
                y,
                &format!("RTO demonstrated: {rto}s"),
            );
            let _ = y; // suppress unused warning on last assignment
        }
    }

    // Footer
    write_text(
        &layer,
        &font,
        FONT_SIZE_SMALL,
        MARGIN_MM,
        MARGIN_MM,
        "Page 3 — Integrity & Compliance Mappings",
    );

    // Serialize to bytes
    let mut buf = BufWriter::new(Vec::new());
    doc.save(&mut buf)
        .map_err(|e| crate::Error::Evidence(format!("Failed to write PDF: {e}")))?;
    let bytes = buf
        .into_inner()
        .map_err(|e| crate::Error::Evidence(format!("Failed to flush PDF buffer: {e}")))?;
    Ok(bytes)
}

fn write_text(
    layer: &PdfLayerReference,
    font: &IndirectFontRef,
    size: f32,
    x_mm: f32,
    y_mm: f32,
    text: &str,
) {
    layer.use_text(text, size, Mm(x_mm), Mm(y_mm), font);
}
